export const jwtConstants = {
  secret: 'eyJzdWIiOjM4MDQwMjU3ODE0NTU2NjcyMCwidW5pX3RlbmFudCI6IjkwMTQiLCJleHQub3JnSWQiOiIwMDAxIiwiZXh0Lm9yZ0NvZGUiOiIwMDAxIiwidHlwZ',
  refreshSecret:
    'eyJzdWIiOjM4MDQwMjU3ODE0NTU2NjcyMCwidW5pX3Rlstaw23jkwMTQiLCJleHQub3JnSWQiOiIwMDAxIiwiZXh0Lm9yZ0NvZGUiOiIwMDAxIiwidHlwZ'
};
