/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleItem: typeof import('./src/components/ArticleItem/index.vue')['default']
    AuthorCard: typeof import('./src/components/AuthorCard/index.vue')['default']
    BlogInfo: typeof import('./src/components/BlogInfo/index.vue')['default']
    Comment: typeof import('./src/components/Comment/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElRow: typeof import('element-plus/es')['ElRow']
    Header: typeof import('./src/components/Header/index.vue')['default']
    Images: typeof import('./src/components/Images/index.vue')['default']
    Notice: typeof import('./src/components/Notice/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialList: typeof import('./src/components/SocialList/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    Title: typeof import('./src/components/Title/index.vue')['default']
    Waves: typeof import('./src/components/Waves/index.vue')['default']
    WebInfo: typeof import('./src/components/WebInfo/index.vue')['default']
  }
}
